### ISSUE TITLE
Do not seperate between holder and presenter

### ISSUE THREAD

**Issue by nikosft** [awoie/rwot11-the-hague#13]
The section "Problem to solve" uses the terms `presenter` and `holder`. IMHO these two are the same entities in the VCDM.

**Comment by RieksJ** [comment]
Correct. The term 'presenter' is used only once in VCDM (in the definition of '[verification](https://www.w3.org/TR/vc-data-model/#dfn-verify)', but is isn't defined. The context suggests that it is the holder executing its task of presenting a presentation.

I suggest we don't bother about what VCDM does in terms of terminology, but that we define our own and document that. And only if there is a benefit for our readers do we relate a term to something else out there, such as a VCDM.

**Comment by vongohren** [comment]
@nikosft can you close this issue now, as the paper only mentiones presenter twice: https://docs.google.com/document/d/1_5eXdxsJ3dDMzdmVTkHi0p-PttI1Wa0RPErC9EJ-0SU/edit#
<img width="1366" alt="image" src="https://user-images.githubusercontent.com/1012055/198873828-3b1dbb24-77a8-4e4d-98b9-6877d82e6019.png">


Which is in some notes at the bottom of the paper.
